# Study Overview


## Study Details
- Participants were UCLA undergraduate students, recruited through SONA (Winter Quarter 2024). Recruitment was targeted to attempt to enroll approximately equal numbers of male and female participants. The study included questionnaires (full list below) that were primarily targeting at understanding current interoceptive and affective functioning, as well as previous early-life and pubertal experiences. 

## Questionnaires

- **College Demographics**
  - BAB Lab
  
  
- **Childhood Trauma Questionnaire**
  - Pennebaker, J. W., & Susman, J. R. (1988). Disclosure of traumas and psychosomatic processes. Social science & medicine, 26(3), 327-332.


- **Interoceptive Accuracy Scale (IAS)**
  - Murphy, J., Brewer, R., Plans, D., Khalsa, S. S., Catmur, C., & Bird, G. (2020). Testing the independence of self-reported interoceptive accuracy and attention. Quarterly Journal of Experimental Psychology, 73(1), 115-133.


- **Multidimensional Assessment of Interoceptive Awareness 2 (MAIA-2)**
  - Mehling WE, Acree M, Stewart A, Silas J, Jones A (2018) The Multidimensional Assessment of Interoceptive Awareness, Version 2 (MAIA-2). PLoS ONE 13(12): e0208034.
  
  
- **Interoceptive Confusion Questionnaire (ICQ)**
  - Brewer, R., Cook, R., & Bird, G. (2016). Alexithymia: a general deficit of interoception. Royal Society open science, 3(10), 150664.


- **CES-D**
  - Radloff, L. S. (1977). The CES-D scale: A self-report depression scale for research in the general population. Applied psychological measurement, 1(3), 385-401.


- **Puberty & Contraceptive Questions**
  - Clare McCann


- **Questionnaire of Unpredictability in Childhood (QUIC)**
  - Glynn, L. M., Stern, H. S., Howland, M. A., Risbrough, V. B., Baker, D. G., Nievergelt, C. M., ... & Davis, E. P. (2019). Measuring novel antecedents of mental illness: the Questionnaire of Unpredictability in Childhood. Neuropsychopharmacology, 44(5), 876-882.


- **Emotions as a Child Questionnaire (EAC)**
  - Magai C, & O’Neal CR (1997). Emotions as a child (child version). Unpublished manuscript, Long Island University, Brooklyn.


- **Toronto Alexithymia Scale (TAS-20)**
  - Bagby, R. M., Parker, J. D., & Taylor, G. J. (1994). The twenty-item Toronto Alexithymia Scale—I. Item selection and cross-validation of the factor structure. Journal of psychosomatic research, 38(1), 23-32.


- **State Trait Anxiety Inventory (Trait; STAI-T)**
  - Spielberger, C. D. (1989). State-Trait Anxiety Inventory: Bibliography (2nd ed.). Palo Alto, CA: Consulting Psychologists Press.
  - Spielberger, C. D., Gorsuch, R. L., Lushene, R., Vagg, P. R., & Jacobs, G. A. (1983). Manual for the State-Trait Anxiety Inventory. Palo Alto, CA: Consulting Psychologists Press.


## Funding
N/A
